### ISSUE TITLE
lab extension should help avoid various obvious mistakes while adding tests

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#98]
* [x] ~~Doesn't make sense to add tests to a non-code cell. (Maybe covered enough by "test class generation failure": `ValueError: Cell 3 is not a code cell, but metadata contains test code!`. Currently only in the logs, but that's a general issue - #154)~~ #182
* [x] ~~What happens when changing cell type (e.g. from source to markdown - presumably shouldn't just permanently wipe out the cell's test, since someone might switch the type by mistake...)?~~ #181
* [x] ~~What happens when clicking to a new cell without saving the tests (they are just lost?)~~ #180
* [x] Indicate if `%cell` is missing? (Covered by requiring deliberate skip, and by warning attached to any test with a skipped cell)
* [x] ~~When you click through cells while looking at the "CELLTESTS" box, you can't tell if you've actually written a test without expanding 'advanced tools' and looking at the 'cell metadata'.~~ #183
* [x] ~~There's no distinction between the "CELLTESTS" box and the "CELLTESTS - RULES" box in terms of tests vs. lint.~~ #184

Dealing with this first in nbcelltests, but after that, the lab extension should be improved.

**Comment by ceball** [comment]
nbcelltests itself now helps with these things underneath, but have opened issues for the (important!) work of making the frontend a bit less hostile.
